timeout: 3

/LCL OS
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    initrd_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=tty0 console=ttyS0,115200 rdinit=/init root=/dev/ram0 lcl.scale=1
    resolution: preferred

/LCL OS (Emergency Debug Shell)
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    module_path: boot():/boot/initramfs.cpio.gz
    initrd_path: boot():/boot/initramfs.cpio.gz
    cmdline: console=tty0 console=ttyS0,115200 rdinit=/init root=/dev/ram0 lcl.scale=1 lcl.debug=1
    resolution: preferred

